# Configuration spécifique pour la production
replicaCount: 2 # On veut de la haute disponibilité en prod

image:
  tag: "alpine" # On force la dernière version en prod

service:
  type: NodePort # On l'expose pour pouvoir y accéder depuis Minikube
